**Name: Anil Bhusal  <br>
Csc 447  <br>
HomeWork 4  <br>
Prof. Erik K. Grimmelmann<br>
07 November 2022**  <br>

### Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from mpl_toolkits import mplot3d
from sklearn import datasets
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import pandas as pd

2022-11-07 10:02:35.111050: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Import the Iris data set

In [2]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target
x_min, x_max = X.min() - 0.5, X.max() + 1.5


### Get Iris classifications

In [3]:
IC = np.unique(Y)
IrisC = ('Setosa','Versicolor','Virginica')
pltC = ('red', 'blue', 'green')
pltCback = ('pink', 'lightblue','lightgreen')
pltM = ('o', 'x', '*')
for i in range(0,3):
    print (IC[i],pltM[i],IrisC[i],pltC[i],pltCback[i])
    


0 o Setosa red pink
1 x Versicolor blue lightblue
2 * Virginica green lightgreen


### Setup Iris feature lablels

In [4]:
IrisF=("sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)")
for i in range(0,4):
    print(IrisF[i])
    
#setting for plots
Xzeros0 = (0. * X) + .2
Xzeros1 = (0. * X) 
Xzeros2 = (0. * X) - .2

sepal length (cm)
sepal width (cm)
petal length (cm)
petal width (cm)


### Function to choose the classes and features to be modeled and return XX and YY arrays

In [5]:
"""
This function will take list of class and lsit of features. 
list of class can be size of two or three classes
list of features can be one to four features
Finally, this function will model the class and feature. And, return array of XX and YY arrays.
where, XX array will include the specified features from the original dataset.
       YY array will include the specified classes from the original dataset.
"""
def build_XX_YY_from_class_and_feature(classes: list, features: list):
    # choose the classes and features to be included in the model
    cdx = np.array(classes)             # this array contains the classes to be considered (can be 2-3 classes)
    fdx = np.array(features)           # this array contains the features to be considered (can be 1-4 features)

    nC = len(cdx)
    nF = len(fdx)


    print ('\nClasses')
    for i in range(nC):
        print (cdx[i],IrisC[cdx[i]])

    print ('\nFeatures')
    for i in range(nF):
        print (fdx[i],IrisF[fdx[i]])


    # build the XX and YY arrays
    # these arrays contain the samples in the classes specified in cdx and include the features specified in fdx

    i = 0
    numY = 0
    for i in range(len(Y)):
        for j in range(nC):
            if Y[i] == IC[cdx[j]]:
                numY += 1

    YY = np.zeros((numY))
    XX = np.zeros((numY,nF))
    if (len(fdx) == 1):
        XXzeros0 = (0. * XX) + .2
        XXzeros1 = (0. * XX) 
        XXzeros2 = (0. * XX) - .2

    j = 0
    for i in range(len(Y)):
        for k in range(nC):
            if Y[i] == IC[cdx[k]]:        
                YY[j] = IC[cdx[k]]
                for m in range(nF):
                    XX[j,m] = X[i,fdx[m]] 
                j += 1
    return XX,YY;

### Combination of classes

In [6]:
#list of all the combination of the three classes
three_classes = [[0,1,2]]              # Choosing 3 classes

### Combination of features

In [7]:
#list of all the combination of the two features
two_feature= [[0,1], [0,2], [0,3],[1,2], [1,3], [2,3]]        # Choosing 2 features

### Fit the model

In [8]:
"""
This function will define a model, compile a model and train the model.  
"""
def fit_model(XX, YY):
    X_train, X_test, y_train, y_test = train_test_split(XX, YY, random_state=0)
    #Define a model
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(3, activation='softmax')
      ])
    #Compile the model
    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    #Train the model
    model.fit(X_train, y_train, batch_size=50, epochs=100)
    y_pred = model.predict(X_test)
    actual = np.argmax(y_test,axis=0)
    predicted = np.argmax(y_pred,axis=0)
    print(y_pred)

### Testing for three classes and two feature. 

In [11]:
for classes in three_classes:
    for feature in two_feature:
        M,N = build_XX_YY_from_class_and_feature(classes,feature)
        fit_model(M, N)


Classes
0 Setosa
1 Versicolor
2 Virginica

Features
0 sepal length (cm)
1 sepal width (cm)
Epoch 1/100
3/3 [==============================] - 0s 2ms/step - loss: 1.3702 - accuracy: 0.3304
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3372 - accuracy: 0.3304
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 1.3085 - accuracy: 0.3304
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 1.2800 - accuracy: 0.3304
Epoch 5/100
3/3 [==============================] - 0s 8ms/step - loss: 1.2578 - accuracy: 0.3304
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2347 - accuracy: 0.3304
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 1.2151 - accuracy: 0.3304
Epoch 8/100
3/3 [==============================] - 0s 8ms/step - loss: 1.1959 - accuracy: 0.3304
Epoch 9/100
3/3 [==============================] - 0s 6ms/step - loss: 1.1810 - accuracy: 0.3304
Epoch 10/100
3/3 [=================

3/3 [==============================] - 0s 2ms/step - loss: 0.9018 - accuracy: 0.6875
Epoch 84/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8984 - accuracy: 0.6875
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8947 - accuracy: 0.6875
Epoch 86/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8916 - accuracy: 0.6875
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8882 - accuracy: 0.6875
Epoch 88/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8846 - accuracy: 0.6875
Epoch 89/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8815 - accuracy: 0.6875
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8777 - accuracy: 0.6875
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8744 - accuracy: 0.6875
Epoch 92/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8705 - accuracy: 0.6875
Epoch 93/100
3/3 [===============

3/3 [==============================] - 0s 2ms/step - loss: 0.5878 - accuracy: 0.7679
Epoch 52/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5812 - accuracy: 0.7768
Epoch 53/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5746 - accuracy: 0.7857
Epoch 54/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5677 - accuracy: 0.7857
Epoch 55/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5610 - accuracy: 0.7857
Epoch 56/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5541 - accuracy: 0.7857
Epoch 57/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5469 - accuracy: 0.7857
Epoch 58/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5398 - accuracy: 0.7857
Epoch 59/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5316 - accuracy: 0.7857
Epoch 60/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5228 - accuracy: 0.7857
Epoch 61/100
3/3 [===============

3/3 [==============================] - 0s 4ms/step - loss: 1.2834 - accuracy: 0.3304
Epoch 15/100
3/3 [==============================] - 0s 4ms/step - loss: 1.2542 - accuracy: 0.3304
Epoch 16/100
3/3 [==============================] - 0s 3ms/step - loss: 1.2271 - accuracy: 0.3304
Epoch 17/100
3/3 [==============================] - 0s 2ms/step - loss: 1.2024 - accuracy: 0.3304
Epoch 18/100
3/3 [==============================] - 0s 4ms/step - loss: 1.1794 - accuracy: 0.3304
Epoch 19/100
3/3 [==============================] - 0s 8ms/step - loss: 1.1585 - accuracy: 0.3304
Epoch 20/100
3/3 [==============================] - 0s 5ms/step - loss: 1.1390 - accuracy: 0.3304
Epoch 21/100
3/3 [==============================] - 0s 4ms/step - loss: 1.1209 - accuracy: 0.3304
Epoch 22/100
3/3 [==============================] - 0s 3ms/step - loss: 1.1044 - accuracy: 0.3304
Epoch 23/100
3/3 [==============================] - 0s 5ms/step - loss: 1.0874 - accuracy: 0.3304
Epoch 24/100
3/3 [===============

3/3 [==============================] - 0s 2ms/step - loss: 0.6031 - accuracy: 0.6964
Epoch 98/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5996 - accuracy: 0.6964
Epoch 99/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5960 - accuracy: 0.6964
Epoch 100/100
2/2 [==============================] - 0s 2ms/step
[[0.0686493  0.2918458  0.63950485]
 [0.38835868 0.29042208 0.32121924]
 [0.87947154 0.06844659 0.0520818 ]
 [0.12937996 0.34073174 0.5298883 ]
 [0.8393613  0.08996933 0.07066933]
 [0.06442126 0.28456134 0.6510174 ]
 [0.78717905 0.11652774 0.09629325]
 [0.16055188 0.3538664  0.48558173]
 [0.21145514 0.34469178 0.4438531 ]
 [0.19297154 0.35365838 0.45337003]
 [0.16027264 0.3556714  0.48405606]
 [0.15208252 0.35225552 0.49566203]
 [0.2521916  0.33739984 0.41040856]
 [0.1540821  0.3530407  0.49287724]
 [0.16027264 0.3556714  0.48405606]
 [0.8643557  0.07745317 0.05819118]
 [0.14427799 0.34898144 0.50674057]
 [0.18699683 0.35803595 0.45496726]
 [0.76

Epoch 65/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6936 - accuracy: 0.6964
Epoch 66/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6877 - accuracy: 0.6964
Epoch 67/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6819 - accuracy: 0.6964
Epoch 68/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6762 - accuracy: 0.6964
Epoch 69/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6706 - accuracy: 0.6964
Epoch 70/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6649 - accuracy: 0.6964
Epoch 71/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6594 - accuracy: 0.6964
Epoch 72/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6541 - accuracy: 0.6964
Epoch 73/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6488 - accuracy: 0.6964
Epoch 74/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6434 - accuracy: 0.6964
Epoch 75/100
3/3 [==

3/3 [==============================] - 0s 2ms/step - loss: 0.8827 - accuracy: 0.6964
Epoch 34/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8787 - accuracy: 0.6964
Epoch 35/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8745 - accuracy: 0.6964
Epoch 36/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8704 - accuracy: 0.6964
Epoch 37/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8661 - accuracy: 0.6964
Epoch 38/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8618 - accuracy: 0.6964
Epoch 39/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8579 - accuracy: 0.6964
Epoch 40/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8533 - accuracy: 0.6964
Epoch 41/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8490 - accuracy: 0.6964
Epoch 42/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8444 - accuracy: 0.6964
Epoch 43/100
3/3 [===============

3/3 [==============================] - 0s 3ms/step - loss: 1.5488 - accuracy: 0.3304
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 1.4952 - accuracy: 0.3304
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 1.4422 - accuracy: 0.4196
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3991 - accuracy: 0.5982
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3531 - accuracy: 0.5893
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3139 - accuracy: 0.5625
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 1.2805 - accuracy: 0.5625
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 1.2461 - accuracy: 0.5446
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 1.2176 - accuracy: 0.3661
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 1.1909 - accuracy: 0.3036
Epoch 11/100
3/3 [=======================

3/3 [==============================] - 0s 3ms/step - loss: 0.8726 - accuracy: 0.5179
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8695 - accuracy: 0.5357
Epoch 86/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8662 - accuracy: 0.5714
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8629 - accuracy: 0.5893
Epoch 88/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8592 - accuracy: 0.5893
Epoch 89/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8551 - accuracy: 0.6607
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8512 - accuracy: 0.6607
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8470 - accuracy: 0.6696
Epoch 92/100
3/3 [==============================] - 0s 2ms/step - loss: 0.8426 - accuracy: 0.6696
Epoch 93/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8381 - accuracy: 0.6696
Epoch 94/100
3/3 [===============

## <center> Observation/Discussion </center> 

In this assignmewnt we have choosen the iris data set for our analysis like last assignments which includes 50 samples from each of the three species. we have also choose the combination of three classses with two features. Thus, we will have six different results and we will be comapring the results with Support Vector Machine with a liner kernel on the same data with the same features. We have already calculate the accuracy for the Support Vector Machine with a liner kernel which is shown below in the table. 

Classes/Features | Sepal Length & Sepal Width | Sepal Length & Petal Length  | Sepal Length & Petal Width | Sepal Width & Petal Length  | Sepal Width & Petal Width | Petal Length & Petal Width 
----|------|--------|-------|-------------|------------|--------------- 
SVC (Linear)|82|95.34|96   |96   |96|96.67 


From above table we see that the Support Vector Machine with a liner kernel have different acccuracies for different combination of the features. The accuracy is highest with the combination of petal length and petal width. The lowest accuracy is with sepal length and sepal width. Three combination has the same accuracy level they are sepal length and petal width, sepal width and petal length, and sepal width and petal width with the accuracy of 96. sepal length and petal width has little change in accuracy with 95.34. We will compare all the combination of the feature and class applying a neural network and using TensorFlow to predict the species of each sample. <br> <br>
To apply a neural network and TensorFlow to predict the species of each sample, we initially imported the libaries, imported iris data set, set up data set to evaluate the specific class and feature, and finally apply a neural network and TensorFlow. After setting the dataset, we define the model. we use Keras sequential to define the model with activation of relu and softmax. After that we compile the defined model with the optimizer as adam, loss function as sparse_categorical_crossentropy. Initally, when we were compiling the model with categorical_crossentropy we were tackling with error as "ValueError: Shapes (None, 1) and (None, 3) are incompatible". But the problem was solve on using sparse_categorical_crossentropy. Finally, after defining and compiling the model we train the model to get the accuracies and our results. We use batch size of 50 and epochs as 100 while fiting our model. We also did the predict the species of each sample. The accuracies of the two features and three class combination is shown below table. 


Classes/Features | Sepal Length & Sepal Width | Sepal Length & Petal Length  | Sepal Length & Petal Width | Sepal Width & Petal Length  | Sepal Width & Petal Width | Petal Length & Petal Width 
----|------|--------|-------|-------------|------------|--------------- 
Tenser overflow |68.75 | 92.86 |69.64 | 75.54 | 87.50 |69.64

After applying a neural network and TensorFlow, we get the different accuracies for our combination of three classes with two features. We get the highest accuracies for the combination of Sepal length and petal length. we get the lowest accuracies for Sepal Length and Sepal Width. we get second and third highest accuracies as Sepal width and petal width, Sepal width and petal length respectivly. We get the same accuracies of the combination of Sepal lenght & Petal Width  and Petal Length & Petal Width, with accuracies of 60.64. Looking at the overal changes of SVC (Linear) and Tenser overflow accuracies, we found that the accuries for all the combination is lower for Tensor overflow. Even the highest accuries combination changes, the lowest remain same i.e. Sepal Length & Sepal Width	still have the lowest accuracies among all the combination we get in our analysis. 

## <center> The End </center> 